AWSTemplateFormatVersion: 2010-09-09
Description: stack for meaning finder app
Parameters:
  ArtifactBucket:
    Type: String
    Description: bucket name for lambda artifacts
  ArtifactBucketKey:
    Type: String
    Description: bucket key for lambda artifacts
Resources:

  InputTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: where-things-begin
      Subscription:
      - Endpoint: !GetAtt MeaningFinderLambda.Arn
        Protocol: lambda

  OutputQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: where-things-end-up

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: allower
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: "translate"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - translate:*
                  - comprehend:*
                Resource: '*'
        - PolicyName: "post-to-queue"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - sqs:SendMessage
                  - sqs:GetQueueUrl
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                Resource: !GetAtt OutputQueue.Arn
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"

  MeaningFinderLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: thing-which-does-stuff
      Handler: dist/index.handler
      Role: !GetAtt LambdaRole.Arn
      Code:
        S3Bucket: !Ref ArtifactBucket
        S3Key: !Sub "${ArtifactBucketKey}/dist.zip"
      Runtime: nodejs14.x
      Timeout: 300
      Environment:
        Variables:
          QUEUE_URL: !Ref OutputQueue

  LambdaSubscriptionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt MeaningFinderLambda.Arn
      Principal: sns.amazonaws.com
      SourceArn: !Ref InputTopic
