AWSTemplateFormatVersion: "2010-09-09"
Description: stack for deploying lambda artifacts bucket
Parameters:
  ArtifactBucketName:
    Type: String
    Description: bucket name for lambda artifacts

Resources:
  ArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref ArtifactBucketName
      Tags:
        - Key: Service
          Value: FunWithCdk

  ArtifactsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ArtifactsBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS:  arn:aws:iam::765096330323:root
            Action:
              - s3:*
            Resource: !Sub arn:aws:s3:::${ArtifactBucketName}/*


